### ISSUE TITLE
[FEATURE] Date and Date/time Display

### ISSUE THREAD

**Issue by roanbear** [SFDO-Community/sticky-selectron#4]
Right now displaying date or date/time fields is not particularly user friendly.

<img width="179" alt="image" src="https://user-images.githubusercontent.com/37357324/228593223-5164e402-1137-4377-b0e9-6495061bf2a4.png">

Ideally date and date/time fields would display in the running user's configuration so that it's the familiar UI experience in the rest of the App.

**Comment by roanbear** [comment]
Do we need an option to display org's date/time vs users?

**Comment by pickettd** [comment]
Should be completed as of 66f600d81fc910bd840485af0d8d2833d2828ddc
