### ISSUE TITLE
[FEATURE] Support Currency Field.

### ISSUE THREAD

**Issue by roanbear** [SFDO-Community/sticky-selectron#45]
**Is your feature request related to a problem? Please describe.**
Currency field display has several issues
- displays amount without currency symbol. 
- doesn't display decimals if they are 00 or if a single decimal like .40 doesn't display the ending 0.

**Describe the solution you'd like**
Consistent display of configured decimal places for the currency field
Currency symbol should display - consider multi-currency implications - likely to display in the record's currency?

**Additional context**
salesforce ui rounds to two decimal places - not sure if we should do this.
Currency and multi-currency is a can of worms.

**Comment by pickettd** [comment]
Should be completed as of 66f600d81fc910bd840485af0d8d2833d2828ddc
