### ISSUE TITLE
[FEATURE] Support Number Field Display

### ISSUE THREAD

**Issue by roanbear** [SFDO-Community/sticky-selectron#46]
**Is your feature request related to a problem? Please describe.**
Number fields don't display decimals if they are 00 or if a single decimal like .40 doesn't display the ending 0.

**Describe the solution you'd like**
Number display should reflect decimal points configured for that number

**Additional context**
same behavior for fomula number fields

**Comment by pickettd** [comment]
Should be completed as of 66f600d81fc910bd840485af0d8d2833d2828ddc
