### ISSUE TITLE
[FEATURE] Improve loading speed for larger record sets

### ISSUE THREAD

**Issue by roanbear** [SFDO-Community/sticky-selectron#49]
**Is your feature request related to a problem? Please describe.**
With larger record-sets the loading is visibly slower than other data table solutions - it could be changes made more recently impacted loading speed and behavior.
Right now the data loads left to right column. Also there may be inconsistencies with the display of the loading graphic. 

**Describe the solution you'd like**
Faster loading, not sure if that means don't load a column at the time or if that part needs to remain the same. Test for loading icon display.  We should benchmark this against other data-tables.

**Comment by pickettd** [comment]
As of 66f600d81fc910bd840485af0d8d2833d2828ddc - it looks like our performance is now returned back to what it was at the time that we introduced Apex (still a little slow on 2000+ records but hopefully we're now at least on par with other datatable solutions)
